config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, presence: true, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  # association
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  # validation
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  # association
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  # validation
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
    @movies = Movie.where.not(id: @list.movies).order(title: :asc)
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      # render :new, status: :unprocessable_entity
      render 'lists/show', status: :unprocessable_entity
    end
  end


  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @list = List.new
    @lists = List.order(name: :asc)
    # raise
  end

  def show
    @bookmark = Bookmark.new
    @movies = Movie.where.not(id: @list.movies).order(title: :asc)
  end

  def new
    @list = List.new
  end

  def create
    @lists = List.all
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      # render :new, status: :unprocessable_entity
      render 'lists/index', status: :unprocessable_entity
    end
  end

  def edit
    # raise
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_card.html.erb
<div class="card-bookmark"
     data-aos="flip-right"
     data-aos-duration="1500"
     <%# data-aos-once="true" %>
     style="background-image: url(<%= bookmark.movie.poster_url %>)">
  <div class="card-content">
    <h2 class="card-title"><%= bookmark.movie.title %></h2>
    <p><i class="fa-solid fa-star"></i> <%= bookmark.movie.rating %></p>
    <p class="card-body"><%= bookmark.comment %></p>
    <%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{bookmark.movie.title}?"}, class: 'card-btn' %>
    <%#= link_to 'See list', list_path(list), class: 'card-btn' %>
    <%#= link_to 'Delete list', list_path(list), class: 'card-btn delete' %>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<div class="form-max-width">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, include_blank: false, collection: @movies %>
    <%= f.input :comment %>
    <%= f.submit 'Add Movie', class: 'black-btn block form-btn'%>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container mt-3">
  <h3>Add a movie to <%= @list.name %></h3>
  <%= render 'bookmarks/form', list: @list, bookmark: @bookmark %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesome Watchlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://unpkg.com/aos@next/dist/aos.css", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner banner-list text-center"
     style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key, :transformation=>[{:height=>800, :width=>1600, :crop=>"fill"},{:effect=>"blur:300"}]) : 'https://images.unsplash.com/photo-1517021897933-0e0319cfbc28?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' %>)">
  <h1><%= list.name %></h1>
  <p><%= "#{pluralize(list.movies.count ,"movie")} in this list." %></p>
  <div class="d-flex gap-3">
    <%# <%= link_to "Edit list", edit_list_path(list), class: 'black-btn' %>

    <button type="button" class="black-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Edit List
    </button>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <%= render 'lists/form', list: list %>
          </div>
        </div>
      </div>
    </div>

    <%= link_to "Delete list", list_path(list), class: 'black-btn', data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{list.name}?"} %>
  </div>
</div>

app/views/lists/_card.html.erb
<div class="card-list"
     data-aos="zoom-in"
     data-aos-once="true"
     style="background-image: url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : 'https://images.unsplash.com/photo-1517021897933-0e0319cfbc28?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' %>)">
  <div class="card-content">
    <h2 class="card-title"><%= list.name %></h2>
    <p class="card-body"><%= "#{ pluralize(list.bookmarks.count, 'movie')}" %></p>
    <%= link_to 'See list', list_path(list), class: 'card-btn' %>
  </div>
</div>

app/views/lists/_form.html.erb
<div class="form-max-width">
  <%= simple_form_for(list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "black-btn form-btn" %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<div class="container mt-4">
<h1>Edit a <%= @list.name %></h1>
<%= render 'lists/form', list: @list %>
</div>

app/views/lists/index.html.erb
<div class="banner text-center"
     style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80)">
  <h1>Awesome Watchlist</h1>
</div>

<%# <div class="mt-3 mb-5"> %>
  <%# <%= render 'lists/form', list: @list %>
<%# </div> %>
<div class="d-flex justify-content-center my-4">
  <button type="button" class="black-btn" data-bs-toggle="modal" data-bs-target="#listForm">
    Add a List
  </button>
</div>

<div class="modal fade" id="listForm" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= render 'lists/form', list: @list %>
      </div>
    </div>
  </div>
</div>

<div class="cards">
  <% @lists.each do |list| %>
    <%= render 'lists/card', list: list %>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container mt-4">
<h1>Create a list</h1>
<%= render 'lists/form', list: @list %>
</div>

app/views/lists/show.html.erb
<%= render 'lists/banner', list: @list %>
<%#= link_to "Add Bookmark", new_list_bookmark_path(@list) %>

<% if @list.movies.empty? %>
  <div class="container mt-5 text-center justify-content-center align-items-center">
    <p>No bookmarks here yet...</p>
  </div>
<% end %>

<div class="d-flex justify-content-center my-4">
  <button type="button" class="black-btn" data-bs-toggle="modal" data-bs-target="#bookmarkForm">
    Add a movie
  </button>
</div>

<div class="modal fade" id="bookmarkForm" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
      </div>
    </div>
  </div>
</div>

<div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
    <%= render 'bookmarks/card', bookmark: bookmark %>
  <% end %>
</div>

<%# <hr class="my-4"> %>
<%# <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
<%# <div class="mt-5"></div> %>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-dark bg-black justify-content-center">
  <div class="container-fluid justify-content-center">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="fa-solid fa-film"></i> Awesome
    <% end %>
  </div>
</nav>